# Generated by Django 4.2.14 on 2024-07-10 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="myuser",
            name="bio",
            field=models.TextField(blank=True, verbose_name="Биография"),
        ),
    ]
