# Generated by Django 4.2.14 on 2024-10-14 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_myuser_bio"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="myuser",
            options={},
        ),
        migrations.AddConstraint(
            model_name="myuser",
            constraint=models.UniqueConstraint(
                fields=("username", "email"), name="unique_follow"
            ),
        ),
    ]
