# Generated by Django 4.2.14 on 2024-07-10 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("gallery", "0002_alter_post_category"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="category",
            name="is_published",
        ),
    ]
